Program 0x0A
Capacity 50
Unk1f "b_70"
Spawn "b_20"

Program 0x0B
Capacity 50
Unk1f "b_71"
Spawn "b_21"

Program 0x01
Capacity 50
Spawn "b_00"

Program 0x02
Capacity 50
Spawn "b_01"

Program 0x03
Capacity 50
Spawn "b_02"

Program 0x23
Capacity 50
Spawn "b_70"

Program 0x24
Capacity 50
Spawn "b_70"

Program 0x19
Spawn "z_70"

Program 0x35
Capacity 45
Party W_FRIEND
Mission 0x6F "NM06_MS102"
Spawn "b_40"